### ISSUE TITLE
Django 2.2 and PostgreSQL 11

### ISSUE THREAD

**Issue by charettes** [tbicr/django-pg-zero-downtime-migrations#5]
First thanks for this project!

It'd be great to see if the warnings/errors scheme on unsafe operation is something that could be integrated to Django's core.

I just wanted to give you a small heads up that the `DatabaseSchemaEditor` schema editor will change a bit in Django 2.2 to allow for check and unique constraint additions through the `Meta.constraints` API. Most of the details are in https://github.com/django/django/pull/10406

Also PostgreSQL 11 allows non locking `NOT NULL` column addition so it'd be great to adjust the documentation in consequence and use `pg_version` detection to avoid raising an exception/warning when not necessary.

**Comment by tbicr** [comment]
Hi, @charettes

I'll see 3 different issues in your:

1. A bit unclear what warnings/errors you propose to integrate to Django's core, because standard postgres backend extend base backend, but for different databases this warnings can be different.

So I can help you to highlight potential unsafe operations for postgres. But I cannot to decide to add it to django core. 

2. I'll look at `DatabaseSchemaEditor` a bit later. Will keep you updated.

3. About postgres 11 it's save to add `DEFAULT` value but standard django's behavior use it only to set all values in new column and than drop `DEFAULT`, see example:

```class Migration(migrations.Migration):

    dependencies = [
        ('yyy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test2',
            field=models.CharField(default='test', max_length=10),
        ),
    ]
```

Will execute next SQL:

```LOG:  statement: BEGIN
LOG:  statement: ALTER TABLE "yyy_test" ADD COLUMN "test2" varchar(10) DEFAULT 'test' NOT NULL
LOG:  statement: ALTER TABLE "yyy_test" ALTER COLUMN "test2" DROP DEFAULT
LOG:  statement: COMMIT
```

If you try to insert any new row to this table from old code (that doesn't know about new changes yet), then you will get exception that `test2` column required. So unfortunately postgres 11 doesn't bring much for current django logic.

**Comment by charettes** [comment]
Ahh you're right about the weird way Django deals with database level defaults. This is already tracked in https://code.djangoproject.com/ticket/470 which you might want to CC.

**Comment by tbicr** [comment]
Hi, @charettes , I created https://github.com/django/django/pull/10789 (https://code.djangoproject.com/ticket/30060#ticket) and https://github.com/tbicr/django-pg-zero-downtime-migrations/pull/6 for django 2.2 support.

**Comment by tbicr** [comment]
django 2.2 support added in https://github.com/tbicr/django-pg-zero-downtime-migrations/pull/6

**Comment by charettes** [comment]
Thanks for all your hardwork, @tbicr!
